name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: report.pdf
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install-pytest
        run: pip3 install pytest

      - name: actions-pytest
        uses: xoviat/actions-pytest@0.1-alpha2
