name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install-pytest
        run: pip3 install pytest

      - name: actions-pytest
        uses: xoviat/actions-pytest@0.1-alpha2
